### ISSUE TITLE
AttributeError: 'str' object has no attribute 'Service'

### ISSUE THREAD

**Issue by joaogqueiroz** [soapteam/soapfish#118]
Does anybody is having this error?

It's the soap.py class that cames with the lib, but I don't change nothing in this.

In my client class I have the same erro but, I've just change the word "self", for the class(CalculatorSoapServiceStub) and works.
Now  stopping in this class and I really don't know what to do.

I'm using:
Flask==1.1.2
Python 3.8.3

<details>
<summary>Copy of <code>soapfish/soap.py</code></summary>

```

"""SOAP protocol implementation, dispatchers and client stub."""

import logging
import string

import requests

from . import core, namespaces as ns, soap11, soap12, wsa
from .utils import uncapitalize

SOAP_HTTP_Transport = ns.wsdl_soap_http

logger = logging.getLogger('soapfish')


class SOAPVersion:
    SOAP11 = soap11
    SOAP12 = soap12

    @classmethod
    def get_version(cls, namespace):
        if namespace == cls.SOAP11.ENVELOPE_NAMESPACE or namespace == cls.SOAP11.BINDING_NAMESPACE:
            return cls.SOAP11
        elif namespace == cls.SOAP12.ENVELOPE_NAMESPACE or namespace == cls.SOAP12.BINDING_NAMESPACE:
            return cls.SOAP12
        else:
            raise ValueError("SOAP version with namespace '%s' is not supported." % namespace)

    @classmethod
    def get_version_name(cls, namespace):
        return cls.get_version(namespace).__name__

    @classmethod
    def get_version_from_xml(cls, xml):
        namespaces = {'wsdl': ns.wsdl, 'soap12': ns.wsdl_soap12}
        return cls.SOAP12 if xml.xpath('wsdl:binding/soap12:binding', namespaces=namespaces) else cls.SOAP11


class Service:
    """Describe service aggregating information required for dispatching and WSDL generation."""

    def __init__(self, targetNamespace, location, schemas, methods, version=SOAPVersion.SOAP11, name='Service',
                 input_header=None, output_header=None, use_wsa=False):
        self.name = name
        self.targetNamespace = targetNamespace
        self.location = location
        self.schemas = schemas
        self.methods = methods
        self.version = version
        self.use_wsa = use_wsa
        if use_wsa and input_header is None:
            input_header = wsa.WSAsaHeader
        if use_wsa and output_header is None:
            output_header = wsa.WSAHeader
        self.input_header = input_header
        self.output_header = output_header

    def get_method(self, operationName):
        return next(m for m in self.methods if m.operationName == operationName)

    def find_element_by_name(self, name):
        element = None
        for schema in self.schemas:
            element = schema.get_element_by_name(name)
            if element is not None:
                break
        return element

    def route(self, operationName):
        """Return a decorator that binds a Python function to service method."""
        method = self.get_method(operationName)

        def wrapper(func):
            method.function = func
            return func

        return wrapper


class Stub:
    """Client stub. Handles only document style calls."""

    SERVICE = None
    SCHEME = 'http'
    HOST = 'www.example.net'

    def __init__(self, username=None, password=None, service=None, location=None):
        self.username = username
        self.password = password
        self.service = service if service else self.SERVICE

        context = {'scheme': self.SCHEME, 'host': self.HOST}
        if location is None:
            location = lambda template, context: string.Template(template).safe_substitute(**context)

        if callable(location):
            self.location = location(self.service.location, context)
        elif isinstance(location, str):
            self.location = location
        else:
            raise TypeError('Expected string or callable for location.')

    def _handle_response(self, method, http_headers, content):
        soap = self.service.version
        envelope = soap.Envelope.parsexml(content)

        if envelope.Header and method and method.output_header:
            response_header = envelope.Header.parse_as(method.output_header)
        else:
            response_header = None

        if envelope.Body.Fault:
            code, message, actor = soap.parse_fault_message(envelope.Body.Fault)
            error = core.SOAPError(code=code, message=message, actor=actor)
            raise error

        if isinstance(method.output, str):
            _type = self.service.find_element_by_name(method.output)._type.__class__
        else:
            _type = method.output

        body = envelope.Body.parse_as(_type)
        return core.SOAPResponse(body, soap_header=response_header)

    def call(self, operationName, parameter, header=None):
        soap = self.service.version
        method = self.service.get_method(operationName)
        tagname = method.input if isinstance(method.input, str) else uncapitalize(parameter.__class__.__name__)

        auth = (self.username, self.password) if self.username else None
        data = soap.Envelope.response(tagname, parameter, header=header)
        headers = soap.build_http_request_headers(method.soapAction)

        logger.info("Call '%s' on '%s'", operationName, self.location)
        logger.debug('Request Headers: %s', headers)
        logger.debug('Request Envelope: %s', data)
        r = requests.post(self.location, auth=auth, headers=headers, data=data)
        logger.debug('Response Headers: %s', r.headers)
        logger.debug('Response Envelope: %s', r.content)
        return self._handle_response(method, r.headers, r.content)

```

</details>

**Comment by pope1ni** [comment]
Please paste the full traceback for the exception. (You've included a copy of `soapfish/soap.py` which is unnecessary.)

**Comment by joaogqueiroz** [comment]
```
Traceback (most recent call last):
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\soapfish\flask_.py", line 14, in flask_dispatch
    soap_response = soap_dispatcher.dispatch(soap_request)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\soapfish\soap_dispatch.py", line 175, in dispatch
    return self.handle_soap_request(request)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\soapfish\soap_dispatch.py", line 186, in handle_soap_request
    response = self.middleware()(request)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\soapfish\soap_dispatch.py", line 20, in call_method
    response = request.method.function(request, request.soap_body)
  File "C:\Users\joaog\Desktop\dev\python_parse\math\server_math.py", line 144, in Add
    CalculatorSoapServiceStub.Add(Add, None)
  File "C:\Users\joaog\Desktop\dev\python_parse\math\client_math.py", line 203, in Add
    return CalculatorSoapServiceStub.call('Add', Add, header)
  File "C:\Users\joaog\Desktop\dev\python_parse\ambvir\Lib\site-packages\soapfish\soap.py", line 126, in call
    soap = self.service.version
AttributeError: 'str' object has no attribute 'service'
```

**Comment by joaogqueiroz** [comment]
I basically trying to do a proxy soap service, so my server will call the service and it will call the final enpoint and return the answear.

I'm using this endpoint to provide my classes(http://www.dneonline.com/calculator.asmx?wsdl)


Server
```
def Add(request, Add):
    CalculatorSoapServiceStub.Add(Add, None)
    return AddResponse

```
Client

```
class CalculatorSoapServiceStub(soap.Stub):
    SERVICE = CalculatorSoap_SERVICE
    SCHEME = 'http'
    HOST = 'www.dneonline.com'

    def Add(self, Add, header=None):
        print(self, Add,None)
        return CalculatorSoapServiceStub.call('Add', Add, header)
```

**Comment by pope1ni** [comment]
You're calling the method without instantiating an object of the stub class:
```python
return CalculatorSoapServiceStub.call('Add', Add, header)
```

If you were to change this to the following it would likely work:
```python
return CalculatorSoapServiceStub().call('Add', Add, header)
```

But you really ought to be using `self` here:
```python
return self.call('Add', Add, header)
```

`self` will refer to the current instance of `CalculatorSoapServiceStub` that you are calling `.Add(...)` on.

**Comment by joaogqueiroz** [comment]
@pope1ni  Tanks man it help me a lot.

I'm a kind of noob in python, I really try to call like you suggest but i was reciving an erro so I prefer to call the class in a direct form.

When i finish my tests I'll try a pull request tutorial with flask to help the community.

Thanks again.

**Comment by pope1ni** [comment]
> I prefer to call the class in a direct form.

Methods are bound on instantiated objects. The first argument is typically named `self` by convention (or `cls` if you're using `@classmethod`).

When you do `self.call(…)` here, `self` is implicitly passed as the first argument giving the method a reference to the object it was called on.

You can call a method from the class, but then you need to explicitly pass the object for the `self` argument as the method is not bound to the object:

```python
class Number:

    def __init__(self, value):
        self.value = value

    def add(self, value):
        self.value += value

obj = Number (1)

obj.add(2)
Number.add(obj, 2)  # ← note that we pass obj here.

print(obj.value)  # 5
```

This is rarely needed, however. I suggest doing some more reading and tutorials on Python classes.
